const crypto = require('crypto');


// Encrypting data
// const algorithm = 'aes-192-cbc';
// const password = 'Password generated by the key';
// const key = crypto.scryptSync(password, 'salt', 24);
// const cipher = crypto.createCipher(algorithm, key);

// let encrypted = '';
// cipher.on('readable', () => {
//   let chunk;
//   while (null !== (chunk = cipher.read())) {
//     encrypted += chunk.toString('hex');
//   }
// });
// cipher.on('end', () => console.log(encrypted));

// cipher.write('some clear text data');
// cipher.end();


// Decrypting data
const algorithm = 'aes-192-cbc';
const password = 'Password generated by the key';
const key = crypto.scryptSync(password, 'salt', 24);
const decipher = crypto.createDecipher(algorithm, key);

let decrypted = '';
decipher.on('readable', () => {
  let chunk;
  while (null !== (chunk = decipher.read())) {
    decrypted += chunk.toString('utf8');
  }
});
decipher.on('end', () => console.log(decrypted));

const encrypted = 'a0c9ff59046106b5ae04b0d3e32106af18408181b256085f4dc8f5a891f17ff5';
decipher.write(encrypted, 'hex');
decipher.end();